# Generated by Django 5.2.6 on 2025-09-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficlights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlight',
            name='install_date',
            field=models.DateField(auto_now_add=True, default='2025-09-27'),
            preserve_default=False,
        ),
    ]
