# Generated by Django 5.2.7 on 2025-10-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuators', '0002_alter_evacuation_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuation',
            name='lat',
            field=models.FloatField(default=11072025),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evacuation',
            name='long',
            field=models.FloatField(default=11072025),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evacuation',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
