# Generated by Django 5.2.6 on 2025-09-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_contact_email_alter_contact_image_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='text',
            field=models.TextField(default='Описание по умолчанию'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='inputs',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_desc',
            field=models.CharField(max_length=255),
        ),
    ]
