# Generated by Django 5.2.6 on 2025-09-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_service_text_alter_service_inputs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_desc', models.CharField(max_length=1024)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_desc', models.CharField(max_length=1024)),
                ('text', models.TextField()),
            ],
        ),
    ]
