# Generated by Django 5.2.6 on 2025-09-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_servicerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='user',
        ),
    ]
